import { WbjeeDto } from './wbjee-dto.model';

export const DUMMY_WBJEE_DATA: WbjeeDto[] = [
  { srNo: '1', round: '1', institute: 'ABC Institute', course: 'B.Tech', stream: 'CSE', seatType: 'General', quota: 'Home', category: 'Open', openingRank: '100', closingRank: '500' },
  { srNo: '2', round: '1', institute: 'XYZ College', course: 'B.Tech', stream: 'ECE', seatType: 'OBC', quota: 'Other', category: 'OBC', openingRank: '200', closingRank: '600' },
  { srNo: '3', round: '2', institute: 'LMN University', course: 'B.Sc', stream: 'IT', seatType: 'SC', quota: 'Home', category: 'SC', openingRank: '300', closingRank: '700' },
  { srNo: '4', round: '2', institute: 'PQR College', course: 'B.Tech', stream: 'ME', seatType: 'ST', quota: 'Other', category: 'ST', openingRank: '400', closingRank: '800' },
  { srNo: '5', round: '1', institute: 'DEF Institute', course: 'B.Tech', stream: 'EE', seatType: 'General', quota: 'Home', category: 'Open', openingRank: '120', closingRank: '520' },
  { srNo: '6', round: '2', institute: 'GHI College', course: 'B.Sc', stream: 'Math', seatType: 'OBC', quota: 'Other', category: 'OBC', openingRank: '220', closingRank: '620' },
  { srNo: '7', round: '1', institute: 'JKL University', course: 'B.Tech', stream: 'CSE', seatType: 'SC', quota: 'Home', category: 'SC', openingRank: '320', closingRank: '720' },
  { srNo: '8', round: '2', institute: 'MNO Institute', course: 'B.Tech', stream: 'ECE', seatType: 'ST', quota: 'Other', category: 'ST', openingRank: '420', closingRank: '820' },
  { srNo: '9', round: '1', institute: 'QRS College', course: 'B.Tech', stream: 'ME', seatType: 'General', quota: 'Home', category: 'Open', openingRank: '140', closingRank: '540' },
  { srNo: '10', round: '2', institute: 'TUV University', course: 'B.Sc', stream: 'IT', seatType: 'OBC', quota: 'Other', category: 'OBC', openingRank: '240', closingRank: '640' },
  { srNo: '11', round: '1', institute: 'WXY Institute', course: 'B.Tech', stream: 'EE', seatType: 'SC', quota: 'Home', category: 'SC', openingRank: '340', closingRank: '740' },
  { srNo: '12', round: '2', institute: 'ZAB College', course: 'B.Tech', stream: 'CSE', seatType: 'ST', quota: 'Other', category: 'ST', openingRank: '440', closingRank: '840' },
  { srNo: '13', round: '1', institute: 'CDE University', course: 'B.Tech', stream: 'ECE', seatType: 'General', quota: 'Home', category: 'Open', openingRank: '160', closingRank: '560' },
  { srNo: '14', round: '2', institute: 'FGH Institute', course: 'B.Sc', stream: 'Math', seatType: 'OBC', quota: 'Other', category: 'OBC', openingRank: '260', closingRank: '660' },
  { srNo: '15', round: '1', institute: 'IJK College', course: 'B.Tech', stream: 'ME', seatType: 'SC', quota: 'Home', category: 'SC', openingRank: '360', closingRank: '760' },
  { srNo: '16', round: '2', institute: 'LMN University', course: 'B.Tech', stream: 'EE', seatType: 'ST', quota: 'Other', category: 'ST', openingRank: '460', closingRank: '860' },
  { srNo: '17', round: '1', institute: 'OPQ Institute', course: 'B.Tech', stream: 'CSE', seatType: 'General', quota: 'Home', category: 'Open', openingRank: '180', closingRank: '580' },
  { srNo: '18', round: '2', institute: 'RST College', course: 'B.Sc', stream: 'IT', seatType: 'OBC', quota: 'Other', category: 'OBC', openingRank: '280', closingRank: '680' },
  { srNo: '19', round: '1', institute: 'UVW University', course: 'B.Tech', stream: 'ECE', seatType: 'SC', quota: 'Home', category: 'SC', openingRank: '380', closingRank: '780' },
  { srNo: '20', round: '2', institute: 'XYZ Institute', course: 'B.Tech', stream: 'ME', seatType: 'ST', quota: 'Other', category: 'ST', openingRank: '480', closingRank: '880' },
  { srNo: '21', round: '1', institute: 'ABC College', course: 'B.Tech', stream: 'EE', seatType: 'General', quota: 'Home', category: 'Open', openingRank: '110', closingRank: '510' },
  { srNo: '22', round: '2', institute: 'DEF University', course: 'B.Sc', stream: 'Math', seatType: 'OBC', quota: 'Other', category: 'OBC', openingRank: '210', closingRank: '610' },
  { srNo: '23', round: '1', institute: 'GHI Institute', course: 'B.Tech', stream: 'CSE', seatType: 'SC', quota: 'Home', category: 'SC', openingRank: '311', closingRank: '711' },
  { srNo: '24', round: '2', institute: 'Institute 24', course: 'B.Tech', stream: 'ME', seatType: 'General', quota: 'Home', category: 'Open', openingRank: '2400', closingRank: '2800' },
  { srNo: '25', round: '1', institute: 'Institute 25', course: 'B.Sc', stream: 'CSE', seatType: 'OBC', quota: 'Other', category: 'OBC', openingRank: '2500', closingRank: '2900' },
  { srNo: '26', round: '2', institute: 'Institute 26', course: 'B.Tech', stream: 'ECE', seatType: 'SC', quota: 'Home', category: 'SC', openingRank: '2600', closingRank: '3000' },
  { srNo: '27', round: '1', institute: 'Institute 27', course: 'B.Tech', stream: 'ME', seatType: 'ST', quota: 'Other', category: 'ST', openingRank: '2700', closingRank: '3100' },
  { srNo: '28', round: '2', institute: 'Institute 28', course: 'B.Sc', stream: 'Math', seatType: 'General', quota: 'Home', category: 'Open', openingRank: '2800', closingRank: '3200' },
  { srNo: '29', round: '1', institute: 'Institute 29', course: 'B.Tech', stream: 'CSE', seatType: 'OBC', quota: 'Other', category: 'OBC', openingRank: '2900', closingRank: '3300' },
  { srNo: '30', round: '2', institute: 'Institute 30', course: 'B.Tech', stream: 'ECE', seatType: 'SC', quota: 'Home', category: 'SC', openingRank: '3000', closingRank: '3400' },
];
